export const tracks = [
  {
    cover: './assets/img/covers/Late_Night_Drive.jpg',
    track: "Late Night Drive",
    author: "Alx Beats",
    src: "./assets/audio/Alx Beats - Late Night Drive.mp3",
    time: '1:54',
  },
  {
    cover: './assets/img/covers/Sangria.jpg',
    track: "Sangria",
    author: "Alx Beats",
    src: "./assets/audio/Alx beats - Sangria.mp3",
    time: '2:43',
  },
  {
    cover: './assets/img/covers/Rave.jpg',
    track: "RAVE",
    author: "Dxrk",
    src: "./assets/audio/Dxrk - RAVE.mp3",
    time: '2:49',
  },
  {
    cover: './assets/img/covers/Twilight.jpg',
    track: "Twilight",
    author: "GraveChill",
    src: "./assets/audio/GraveChill - Twilight.mp3",
    time: '1:56',
  },
  {
    cover: './assets/img/covers/Dream.jpg',
    track: "DREAM",
    author: "HOSPICEMANE, purvs",
    src: "./assets/audio/HOSPICEMANE, purvs - DREAM.mp3",
    time: '2:16',
  },
  {
    cover: './assets/img/covers/Murder_In_My_Mind.jpg',
    track: "Murder In My Mind",
    author: "Kordhell",
    src: "./assets/audio/Kordhell - Murder In My Mind.mp3",
    time: '2:25',
  },
  {
    cover: './assets/img/covers/THIS_IS_LOVE.jpg',
    track: "THIS IS LOVE",
    author: "OBLXKQ",
    src: "./assets/audio/OBLXKQ - THIS IS LOVE.mp3",
    time: '2:15',
  },
  {
    cover: './assets/img/covers/ghost.jpg',
    track: "phonk.me, kiixshi",
    author: "ghost",
    src: "./assets/audio/phonk.me, kiixshi - ghost.mp3",
    time: '3:52',
  },
  {
    cover: './assets/img/covers/My_Idol.jpeg',
    track: "PLXYAE",
    author: "My Idol",
    src: "./assets/audio/PLXYAE - My Idol.mp3",
    time: '1:38',
  },
  {
    cover: './assets/img/covers/Unloved.jpg',
    track: "XVNVGE",
    author: "Unloved",
    src: "./assets/audio/XVNVGE - Unloved.mp3",
    time: '3:59',
  },
]